---
id: gunmaweb13
base_name: functional-language-retry
tags:
- functional language
presentation_date: 2013/05/18
version: 2013.05.18
licenses: []
slideshare_id: 
speaker_deck_id: 
author:
  markup_language: :rd
  name: parrot-studio
  email: parrot.studio.dev@gmail.com
  rubygems_user: 
  slideshare_user: parrotstudio
  speaker_deck_user: parrotstudio
